<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="arm_joints.xacro" />

    <xacro:property name="link_0_length" value="0.25" />
    <xacro:property name="link_0_width" value="0.3" />
    <xacro:property name="link_0_height" value="0.02" />

    <xacro:property name="link_1_radius" value="0.04" />
    <xacro:property name="link_1_length" value="0.1" />

    <xacro:property name="link_2_radius" value="0.02" />
    <xacro:property name="link_2_length" value="0.3" />

    <xacro:property name="link_3_radius" value="0.02" />
    <xacro:property name="link_3_length" value="0.15" />

    <material name="LightBlue">
        <color rgba="0.589 0.793 1.0 1.0"/>
    </material>

    <link name="link_0">
        <visual>
            <geometry>
                <box size="${link_0_length} ${link_0_width} ${link_0_height}" />
            </geometry>
            <origin xyz="0 0 ${link_0_height / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <box size="${link_0_length} ${link_0_width} ${link_0_height}" />
            </geometry>
            <origin xyz="0 0 ${link_0_height / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="0.5" l="${2*link_0_length}" w="${2*link_0_width}"
            h="${2*link_0_height}"
            xyz="0 0 ${link_0_height / 2.0}" rpy="0 0 0" />
    </link>

    <joint name="joint_1" type="revolute">
        <parent link="link_0" />
        <child link="link_1" />
        <origin xyz="0 0 ${link_0_height}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="-${pi/4}" upper="${pi/2}" effort="100" velocity="1.0" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>


    <!--=============================================================================-->

    <link name="link_1">
        <visual>
            <geometry>
                <cylinder radius="${link_1_radius}" length="${link_1_length}" />
            </geometry>
            <origin xyz="0 0 ${link_1_length / 2.0}" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${link_1_radius}" length="${link_1_length}" />
            </geometry>
            <origin xyz="0 0 ${link_1_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="10" r="${2*link_1_radius}" h="${2*link_1_length}"
            xyz="0 0 ${link_1_length / 2.0}" rpy="0 0 0" />
    </link>


    <link name="link_1_endlink">
        <xacro:inertial_block mass="${10/3.0}" length="${2*link_1_radius+2*link_2_radius}"
            radius="${link_1_radius}" />
        <visual>
            <origin xyz="0.0 0.0 ${(2*link_1_radius+2*link_2_radius)/2.0}" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${link_1_radius*1.1}"
                    length="${2*link_1_radius+2*link_2_radius}" />
            </geometry>
            <material name="LightBlue" />
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${(2*link_1_radius+2*link_2_radius)/2.0}" rpy="0.0 0.0 0.0" />
            <geometry>
                <cylinder radius="${link_1_radius*1.1}"
                    length="${2*link_1_radius+2*link_2_radius}" />
            </geometry>
        </collision>

    </link>
    
    <joint name="link_1_endjoint" type="fixed">
        <origin xyz="${-link_1_radius} 0.0 ${link_1_length - 0.01}" rpy="0.0 ${pi/2.0} 0.0" />
        <parent link="link_1" />
        <child link="link_1_endlink" />
    </joint>

    <joint name="joint_2" type="revolute">
        <parent link="link_1" />
        <child link="link_2" />
        <!-- <origin xyz="0 0 ${link_1_length}" rpy="0 0 0" /> -->
        <origin xyz="${link_1_radius + link_2_radius} 0.0 ${link_1_length}" rpy="0.0 0.0 0.0" />
        <axis xyz="1 0 0" />
        <limit lower="0" upper="${pi/2}" effort="100" velocity="1.0" />
        <dynamics friction="0.05" damping="0.1" />
    </joint>

    <!--=============================================================================-->


    <link name="link_2">
        <visual>
            <geometry>
                <cylinder radius="${link_2_radius}" length="${link_2_length}" />
            </geometry>
            <origin xyz="0 0 ${link_2_length / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${link_2_radius}" length="${link_2_length}" />
            </geometry>
            <origin xyz="0 0 ${link_2_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*link_2_radius}" h="${2*link_2_length}"
            xyz="0 0 ${link_2_length / 2.0}" rpy="0 0 0" />
    </link>
    
    <link name="link_2_endlink">
        <xacro:inertial_block mass="${0.3/3.0}" length="${2*link_2_radius+2*link_3_radius}" radius="${link_2_radius}"/>
        <visual>
            <origin xyz="0.0 0.0 ${(2*link_2_radius+2*link_3_radius)/2.0}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${link_2_radius*1.1}" length="${2*link_2_radius+2*link_3_radius}"/>
            </geometry>
            <material name="LightBlue"/>
        </visual>

        <collision>
            <origin xyz="0.0 0.0 ${(2*link_2_radius+2*link_3_radius)/2.0}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${link_2_radius*1.1}" length="${2*link_2_radius+2*link_3_radius}"/>
            </geometry>
        </collision>
    </link>

    <joint name="link_2_endjoint" type="fixed">
        <origin xyz="${-link_2_radius} 0.0 ${link_2_length - 0.01}" rpy="0.0 ${pi/2.0} 0.0"/>
        <parent link="link_2"/>
        <child link="link_2_endlink"/>
    </joint>

    <joint name="joint_3" type="revolute">
        <parent link="link_2" />
        <child link="link_3" />
        <!-- <origin xyz="0 0 ${link_2_length}" rpy="0 0 0" /> -->
        <origin xyz="${link_2_radius + link_3_radius} 0.0 ${link_2_length - link_2_radius}" rpy="0.0 0.0 0.0"/>
        <axis xyz="1 0 0" />
        <limit lower="-${pi/2}" upper="${pi/2}" effort="100" velocity="1.0" />
        <dynamics friction="0.05" damping="0.15" />
    </joint>


    <!--=============================================================================-->

    <link name="link_3">
        <visual>
            <geometry>
                <cylinder radius="${link_3_radius}" length="${link_3_length}" />
            </geometry>
            <origin xyz="0 0 ${link_3_length / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${link_3_radius}" length="${link_3_length}" />
            </geometry>
            <origin xyz="0 0 ${link_3_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="0.3" r="${2*link_3_radius}" h="${2*link_3_length}"
            xyz="0 0 ${link_3_length / 2.0}" rpy="0 0 0" />
    </link>

    <!--=============================================================================-->

    <xacro:config_ctr_gazebo />

</robot>